name: build and push image

on:
  push:
    branches:
      - 'main'
    paths:
      - Dockerfile
      - '.github/workflows/**'

env:
  IMAGE_NAME: "simaofsilva/renovatebot-docker-renovate"
  REPO_URL: "https://github.com/renovatebot/docker-renovate"
  LOCAL_PATH: "/tmp/docker-renovate"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version for tag
        id: version
        shell: bash
        run: |
          echo "::set-output name=VERSION::$(sed -n '2p' Dockerfile | sed 's|ARG RENOVATE_VERSION=||1')"

      - name: Print version
        run: |
          echo ${{ steps.version.outputs.VERSION }}

      - name: Clone original repository
        run: |
          git clone ${{ env.REPO_URL }} ${{ env.LOCAL_PATH }}

      - name: Check if custom Dockerfile is been used
        run: |
          cp Dockerfile ${{ env.LOCAL_PATH }}
          cat ${{ env.LOCAL_PATH }}/Dockerfile

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.LOCAL_PATH }}
          platforms: linux/arm64/v8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.version.outputs.VERSION }}-slim
            ${{ env.IMAGE_NAME }}:slim
            ${{ env.IMAGE_NAME }}:latest

  # delete_old_runs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Delete workflow runs
  #       uses: Mattraks/delete-workflow-runs@v2.0.3
  #       with:
  #         token: ${{ github.token }}
  #         repository: ${{ github.repository }}
  #         retain_days: 15
  #         keep_minimum_runs: 5
